### ISSUE TITLE
Error on npm run

### ISSUE THREAD

**Issue by alibaztomars** [HTPGTDev/GrowJS-Project#3]
Node: V18
Platform: Windows 11

Console:

C:\Users\win11\Desktop\GrowJS-Project-main>npm run build

> growserver@2.0.0 build
> tsc

src/actions/JoinRequest.ts:25:32 - error TS2339: Property 'base' does not exist on type 'default'.

25     const worldEntering = this.base.cache.worlds.getWorld(worldName)
                                  ~~~~


Found 1 error in src/actions/JoinRequest.ts:25

**Comment by alibaztomars** [comment]
Guys had to delete "this" from line 25 and it worked.

**Comment by Howtoplay-Games** [comment]
Thank you for spotting this issue.
